// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUiLui6NZuHnf8l1bpUdWiRccTEbX7UY',
    appId: '1:653613258024:web:d5125437c1f6f4527cec1d',
    messagingSenderId: '653613258024',
    projectId: 'ttspeech-5d060',
    authDomain: 'ttspeech-5d060.firebaseapp.com',
    storageBucket: 'ttspeech-5d060.appspot.com',
    measurementId: 'G-NJ5SWLLH4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUZBtiii2wth-MxRp23Lw-U8Apa01otCg',
    appId: '1:653613258024:android:206a1ba55ca05db57cec1d',
    messagingSenderId: '653613258024',
    projectId: 'ttspeech-5d060',
    storageBucket: 'ttspeech-5d060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKulvDgEzDpOahAIxjRVjXA5ed1F3f-U0',
    appId: '1:653613258024:ios:a12eb2e845f3fc467cec1d',
    messagingSenderId: '653613258024',
    projectId: 'ttspeech-5d060',
    storageBucket: 'ttspeech-5d060.appspot.com',
    iosBundleId: 'com.example.tts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKulvDgEzDpOahAIxjRVjXA5ed1F3f-U0',
    appId: '1:653613258024:ios:64f5928e08920d3a7cec1d',
    messagingSenderId: '653613258024',
    projectId: 'ttspeech-5d060',
    storageBucket: 'ttspeech-5d060.appspot.com',
    iosBundleId: 'com.example.tts.RunnerTests',
  );
}
